name: CI
on:
  push:
    branches:
      - main
      
jobs:
  job1: 
    runs-on: ubuntu-latest
    steps:
    - name: start kubectl
      uses: steebchen/kubectl@master
      env:
        KUBE_CONFIG_DATA: ${{ secrets.KUBECONFIG }}  
    - name: connect to K8s cluster
      run:
        kubectl get pods
        
