on: push
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Kubernetes tools
        env: 
          KUBECONFIG=${{ secrets.KUBECONFIG }} | base64 -D
        run:
          echo $KUBECONFIG
