on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Kubernetes tools
        run: | 
          touch ~/.kube/config
          echo ${{ secrets.KUBECONFIG }} | base64 -d > ~/.kube/config
          cat $HOME/.kube/config
