on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Kubernetes tools
        run: | 
          echo ${KUBE_CONFIG_DATA} | base64 -d > kubeconfig
          export KUBECONFIG=kubeconfig
          echo $KUBECONFIG
