on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Kubernetes tools
        run: | 
          KUBECONFIG=${{ secrets.KUBECONFIG }} | base64 -d
          echo $KUBECONFIG
